apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cas-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cas-service.name" . }}
    helm.sh/chart: {{ include "cas-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cas-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cas-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      # Role of writing the CloudWatch logs
      annotations:
        iam.amazonaws.com/role: {{ .Values.aws.role }}
        timestamp: "{{ .Release.Time.Seconds }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /sharedFiles
              name: shared-files
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            failureThreshold: 15
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 3
          env:
            - name: APPDYNAMICS_CONTROLLER_HOST_NAME
              value: {{ .Values.appdynamics.appdynamics_controller_host_name }}
            - name: APPDYNAMICS_CONTROLLER_PORT
              value: {{ .Values.appdynamics.appdynamics_controller_port | quote }}
            - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
              value: {{ .Values.appdynamics.appdynamics_controller_ssl_enabled | quote }}
            - name: APPDYNAMICS_AGENT_APPLICATION_NAME
              value: {{ .Values.appdynamics.appdynamics_agent_application_name }}
            - name: APPDYNAMICS_AGENT_TIER_NAME
              value: {{ .Chart.Name }}
            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME
              value: {{ .Values.appdynamics.appdynamics_java_agent_reuse_node_name | quote }}
            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX
              value: {{ .Chart.Name }}
            - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
              value: {{ .Values.appdynamics.appdynamics_agent_account_name }}
            - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
              value: {{ .Values.appdynamics.appdynamics_agent_account_access_key }}
            - name: db_host
              value: {{ .Values.env.db_host }}
            - name: db_password
              value: {{ .Values.env.db_password }}
            - name: db_username
              value: {{ .Values.env.db_username }}
            - name: db_name
              value: {{ .Values.env.db_name }}
            - name: cas.configuration.scheduler
              value: {{ .Values.env.cas.configuration.scheduler }}
            - name: cas.beneficiary.service.url
              value: {{ .Values.env.cas.beneficiary.service.url }}
            - name: cas.beneficiary.mobile-internal.url
              value: {  .Values.env.cas.beneficiary.mobile-internal.url }}
            - name: cas.benefit.iban-directories.url
              value: {{ .Values.env.cas.benefit.iban-directories.url }}
            - name: cas.auth.client-id
              value: {{ .Values.env.cas.service.inquire.client-id }}
            - name: cas.auth.secretKey
              value: {{ .Values.env.cas.service.inquire.signature }}
            - name: activemq.broker_url
              value: {{ .Values.env.activemq.broker_url }}
            - name: activemq.password
              value: {{ .Values.env.activemq.password }}
            - name: activemq.user
              value: {{ .Values.env.activemq.user }}
            - name: container.ingress.neo.service.trigger
              value: {{ .Values.env.container.ingress.neo.service.trigger }}
            - name: spring.profiles.active
              value: {{ .Values.env.spring.profiles.active }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      - name: appd-agent
        image: 096987977627.dkr.ecr.eu-west-1.amazonaws.com/misc/appd-appserver-agent:latest
        imagePullPolicy: Always
        command: ['cp', '-r', '/sharedFiles/AppServerAgent', '/mountPath/AppServerAgent']
        volumeMounts:
          - mountPath: /mountPath
            name: shared-files
      volumes:
        - name: shared-files
          emptyDir: {}
